- name: Configure/install applications needed to run wordpress(nginx/php/php-fpm/mysql/wordpress)
  hosts: web
  sudo: yes
  tasks:
  - name: Setup nginx.conf file
    template: src=/vagrant/conf/nginx/nginx.conf
              dest=/etc/nginx/nginx.conf
  - name: Setup fastcgi_params file
    template: src=/vagrant/conf/nginx/fastcgi_params
              dest=/etc/nginx/fastcgi_params
  - name: Setup nginx virtualhost config file for wordpress
    template: src=/vagrant/conf/nginx/sites-available/wordpress
              dest=/etc/nginx/sites-available/wordpress
  - name: remove default nginx site
    file:     path=/etc/nginx/sites-enabled/default
              state=absent
  - name: remove default php-fpm site
    file:     path=/etc/php5/fpm/pool.d/www.conf
              state=absent
  - name: Setup nginx virtualhost symbolic link for wordpress
    file:     src=/etc/nginx/sites-available/wordpress
              dest=/etc/nginx/sites-enabled/wordpress
              state=link
  - name: Create nginx root directory for wordpress
    file:     path=/var/www/paralympics
              state=directory
  - name: Setup php-fpm.conf file
    template: src=/vagrant/conf/php5/fpm/php-fpm.conf
              dest=/etc/php5/fpm/php-fpm.conf
  - name: Setup php.ini
    template: src=/vagrant/conf/php5/fpm/php.ini
              dest=/etc/php5/fpm/php.ini
  - name: Setup fpm pool config file for wordpress
    template: src=/vagrant/conf/php5/fpm/pool.d/wordpress.conf
              dest=/etc/php5/fpm/pool.d/wordpress.conf
  - name: Create php5-fpm socket file directory
    file:     path=/var/run/php5-fpm/
              state=directory owner=www-data group=www-data
  - name: Create php5-fpm log directory
    file:     path=/var/log/php5-fpm/log/
              state=directory

- name: Configure database server
  hosts: db
  sudo: yes
  tasks:
  - name: Setup mysql
    template: src=/vagrant/conf/mysql/my.cnf
              dest=/etc/mysql/my.cnf
  - name: Add user 'wp-user' to mysql
    mysql_user: name=wp-user password=""

- name: Configure wordpress
  hosts: wordpress
  sudo: yes
  handlers:
    - name: stop apache2
      service: name=apache2 state=stopped
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart php5-fpm
      service: name=php5-fpm state=restarted
    - name: restart mysql
      service: name=mysql state=restarted
  tasks:
  - name: Create wordpress config directory
    file: path=/etc/wordpress/ state=directory
  - name: Setup wordpress
    git: repo=git://github.com/WordPress/WordPress.git 
         dest=~/downloads/
         version=4.0
         accept_hostkey=yes
    sudo: no
  - name: Download wordpress plugin staticpress
    git: repo=https://github.com/megumiteam/staticpress
         dest=~/downloads/wp-content/plugins/staticpress
         accept_hostkey=yes
    sudo: no
  - name: Download wordpress plugin The Event Calendar
    get_url: url=https://downloads.wordpress.org/plugin/the-events-calendar.3.8.zip dest=/tmp/
  - name: Unzip the-events-calendar plugin
    shell: unzip -o /tmp/the-events-calendar.3.8.zip -d ~/downloads/wp-content/plugins/
    sudo: no
  - name: Fetch random salts for Wordpress config
    local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
    register: "wp_salt"
    sudo: no
  - name: Create Wordpress database
    mysql_db: name=mywp_db state=present
  - name: Create Wordpress database user
    mysql_user: name=wp-user password=""
                priv=*.*:SELECT,INSERT,UPDATE,DELETE,CREATE,ALTER,DROP,INDEX
                host='localhost' state=present
  - name: Copy Wordpress config file
    template: src=/vagrant/conf/wp-config.php dest=/etc/wordpress/
  - name: Install wordpress files to nginx root directory for wordpress
    synchronize: src=~/downloads/
                 dest=/var/www/paralympics/
                 recursive=yes
  - name: Change ownership of Wordpress installation
    file: path=/var/www/paralympics/ owner=www-data group=www-data state=directory recurse=yes
    notify:
      - stop apache2
      - restart mysql
      - restart nginx
      - restart php5-fpm
